# -*- coding: utf-8 -*-
"""AMAZON ML .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rqTVbZ1sBsUyPgobYmi9ORgaYWlbncz6
"""

!git clone https://github.com/ShreeNithiB/Amazon--ML---challenge-

# Commented out IPython magic to ensure Python compatibility.
# %cd Amazon--ML---challenge-

!ls

# ============================================================
# STEP 4.5: RE-INITIALIZE NOTEBOOK IMPORTS
# ============================================================

from pathlib import Path
import re
import unicodedata
import pandas as pd
import numpy as np
import gc
import time
from collections import defaultdict

DATA_DIR = Path("/content/")
OUTPUT_DIR = Path("/kaggle/working/amazon_ml_output")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print("Environment initialized successfully.")
print("DATA_DIR:", DATA_DIR)

from pathlib import Path
import re
import unicodedata
import pandas as pd
import numpy as np
import gc
import time
from collections import defaultdict

# Assuming DATA_DIR is already defined from a previous cell, if not, it should be defined here as well.
# DATA_DIR = Path("/content/")

LEGAL_SUFFIX_MAP = {
    "incorporated": "inc",
    "corporation": "corp",
    "company": "co",
    "limited": "ltd",
    "private": "pvt",
    "llc": "llc",
    "llp": "llp",
}

def normalize_unicode(text):
    if pd.isna(text):
        return ""

    text = str(text)
    text = unicodedata.normalize("NFKC", text)
    text = text.lower()

    return text


def normalize_name(text):
    text = normalize_unicode(text)

    text = re.sub(
        r"[^\\w\\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\\s+",
        " ",
        text
    ).strip()

    tokens = text.split()

    tokens = [
        LEGAL_SUFFIX_MAP.get(token, token)
        for token in tokens
    ]

    return " ".join(tokens)


def build_name_country_index(file_path, chunk_size=250_000):

    index = defaultdict(list)

    start = time.time()
    total_rows = 0

    for chunk in pd.read_csv(
        file_path,
        sep="\\t",
        usecols=[
            "entity_id",
            "business_name",
            "country"
        ],
        chunksize=chunk_size,
        encoding='latin1'
    ):

        chunk["name_norm"] = (
            chunk["business_name"]
            .map(normalize_name)
        )

        for row in chunk.itertuples(index=False):

            if not row.name_norm:
                continue

            key = (
                row.name_norm,
                row.country
            )

            index[key].append(
                row.entity_id
            )

        total_rows += len(chunk)

        print(
            f"Processed {total_rows:,} rows",
            end="\\r"
        )

        del chunk
        gc.collect()

    elapsed = (
        time.time() - start
    ) / 60

    print()

    print(
        f"Processed: {total_rows:,} rows"
    )

    print(
        f"Unique name+country keys: "
        f"{len(index):,}"
    )

    print(
        f"Time: {elapsed:.2f} minutes"
    )

    return index

# Rebuilding Source 3 index with correct DATA_DIR
print("Rebuilding Source 3 index...")
s3_index = build_name_country_index(
    DATA_DIR / "train_source3.tsv"
)

# ============================================================
# STEP 2: NORMALIZATION FUNCTIONS
# ============================================================

LEGAL_SUFFIX_MAP = {
    "incorporated": "inc",
    "corporation": "corp",
    "company": "co",
    "limited": "ltd",
    "private": "pvt",
    "llc": "llc",
    "llp": "llp",
}

def normalize_unicode(text):
    if pd.isna(text):
        return ""

    text = str(text)
    text = unicodedata.normalize("NFKC", text)
    text = text.lower()

    return text


def normalize_name(text):
    text = normalize_unicode(text)

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    tokens = text.split()

    tokens = [
        LEGAL_SUFFIX_MAP.get(token, token)
        for token in tokens
    ]

    return " ".join(tokens)


def normalize_address(text):
    text = normalize_unicode(text)

    replacements = {
        r"\bstreet\b": "st",
        r"\broad\b": "rd",
        r"\bavenue\b": "ave",
        r"\blane\b": "ln",
        r"\bdrive\b": "dr",
        r"\bhighway\b": "hwy",
        r"\bparkway\b": "pkwy",
        r"\bboulevard\b": "blvd",
    }

    for pattern, replacement in replacements.items():
        text = re.sub(
            pattern,
            replacement,
            text
        )

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text


print("Normalization functions ready!")
print(normalize_name("ABC Corporation Pvt. Ltd."))
print(normalize_address("500 Market Street, San Jose"))

# ============================================================
# STEP 3: INDEX BUILDER
# ============================================================

def build_name_country_index(file_path, chunk_size=250_000):

    index = defaultdict(list)

    start = time.time()
    total_rows = 0

    for chunk in pd.read_csv(
        file_path,
        sep="\t",
        usecols=[
            "entity_id",
            "business_name",
            "country"
        ],
        chunksize=chunk_size,
        encoding='latin1'  # Added encoding parameter
    ):

        chunk["name_norm"] = (
            chunk["business_name"]
            .map(normalize_name)
        )

        for row in chunk.itertuples(index=False):

            if not row.name_norm:
                continue

            key = (
                row.name_norm,
                row.country
            )

            index[key].append(
                row.entity_id
            )

        total_rows += len(chunk)

        print(
            f"Processed {total_rows:,} rows",
            end="\r"
        )

        del chunk
        gc.collect()

    elapsed = (
        time.time() - start
    ) / 60

    print()

    print(
        f"Processed: {total_rows:,} rows"
    )

    print(
        f"Unique name+country keys: "
        f"{len(index):,}"
    )

    print(
        f"Time: {elapsed:.2f} minutes"
    )

    return index


print("Index builder ready!")

# ============================================================
# STEP 5: BUILD SOURCE 3 INDEX
# ============================================================

print("Building Source 3 index...")

s3_index = build_name_country_index(
    DATA_DIR / "train_source3.tsv"
)

from pathlib import Path
import re
import unicodedata
import pandas as pd
import numpy as np
import gc
import time
from collections import defaultdict

DATA_DIR = Path("/content/")

LEGAL_SUFFIX_MAP = {
    "incorporated": "inc",
    "corporation": "corp",
    "company": "co",
    "limited": "ltd",
    "private": "pvt",
    "llc": "llc",
    "llp": "llp",
}

def normalize_unicode(text):
    if pd.isna(text):
        return ""

    text = str(text)
    text = unicodedata.normalize("NFKC", text)
    text = text.lower()

    return text


def normalize_name(text):
    text = normalize_unicode(text)

    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    tokens = text.split()

    tokens = [
        LEGAL_SUFFIX_MAP.get(token, token)
        for token in tokens
    ]

    return " ".join(tokens)


def build_name_country_index(file_path, chunk_size=250_000):

    index = defaultdict(list)

    start = time.time()
    total_rows = 0

    for chunk in pd.read_csv(
        file_path,
        sep="\t",
        usecols=[
            "entity_id",
            "business_name",
            "country"
        ],
        chunksize=chunk_size,
        encoding='latin1'
    ):

        chunk["name_norm"] = (
            chunk["business_name"]
            .map(normalize_name)
        )

        for row in chunk.itertuples(index=False):

            if not row.name_norm:
                continue

            key = (
                row.name_norm,
                row.country
            )

            index[key].append(
                row.entity_id
            )

        total_rows += len(chunk)

        print(
            f"Processed {total_rows:,} rows",
            end="\r"
        )

        del chunk
        gc.collect()

    elapsed = (
        time.time() - start
    ) / 60

    print()

    print(
        f"Processed: {total_rows:,} rows"
    )

    print(
        f"Unique name+country keys: "
        f"{len(index):,}"
    )

    print(
        f"Time: {elapsed:.2f} minutes"
    )

    return index

# ============================================================
# STEP 4: BUILD SOURCE 2 INDEX
# ============================================================

print("Building Source 2 index...")

s2_index = build_name_country_index(
    DATA_DIR / "train_source2.tsv"
)

# ============================================================
# STEP 5: BUILD SOURCE 3 INDEX
# ============================================================

print("Building Source 3 index...")

s3_index = build_name_country_index(
    DATA_DIR / "train_source3.tsv"
)

# ============================================================
# STEP 6: VERIFY
# ============================================================

print("s2_index exists:", "s2_index" in globals())
print("s3_index exists:", "s3_index" in globals())
print("normalize_name exists:", "normalize_name" in globals())

print(
    "S2 index keys:",
    len(s2_index)
)

print(
    "S3 index keys:",
    len(s3_index)
)

# ============================================================
# STEP 7: LOAD 10,000 SOURCE 1 RECORDS
# ============================================================

S1_SAMPLE_N = 10_000

s1_sample = pd.read_csv(
    DATA_DIR / "train_source1.tsv",
    sep="\t",
    nrows=S1_SAMPLE_N,
    usecols=[
        "entity_id",
        "business_name",
        "business_address",
        "country"
    ]
)

s1_sample["name_norm"] = (
    s1_sample["business_name"]
    .map(normalize_name)
)

print(
    f"Loaded Source 1 records: "
    f"{len(s1_sample):,}"
)

display(s1_sample.head())

# ============================================================
# STEP 8: GENERATE CANDIDATES
# Blocking rule:
#     normalized business name + country
# ============================================================

candidate_rows = []

start_time = time.time()

for row in s1_sample.itertuples(index=False):

    key = (row.name_norm, row.country)

    # Source 2 candidates
    for candidate_id in s2_index.get(key, []):
        candidate_rows.append({
            "source1_entity_id": row.entity_id,
            "candidate_entity_id": candidate_id,
            "candidate_source": "S2"
        })

    # Source 3 candidates
    for candidate_id in s3_index.get(key, []):
        candidate_rows.append({
            "source1_entity_id": row.entity_id,
            "candidate_entity_id": candidate_id,
            "candidate_source": "S3"
        })

elapsed = time.time() - start_time

candidates = pd.DataFrame(
    candidate_rows,
    columns=[
        "source1_entity_id",
        "candidate_entity_id",
        "candidate_source"
    ]
)

print(f"Candidate generation time: {elapsed:.2f} seconds")
print(f"Total candidate pairs: {len(candidates):,}")

print("\nCandidates by source:")
print(candidates["candidate_source"].value_counts())

print("\nAverage candidates per Source 1:")
print(len(candidates) / len(s1_sample))

# ============================================================
# STEP 9: LOAD GROUND TRUTH
# ============================================================

GT_PATH = DATA_DIR / "train_ground_truth.tsv"

gt = pd.read_csv(
    GT_PATH,
    sep="\t",
    usecols=[
        "source1_entity_id",
        "matched_entity_ids"
    ]
)

gt_sample = gt[
    gt["source1_entity_id"].isin(
        s1_sample["entity_id"]
    )
].copy()

print(f"Ground-truth Source 1 entities: {len(gt_sample):,}")

display(gt_sample.head())

# ============================================================
# STEP 10: EXPLODE GROUND TRUTH INTO MATCH PAIRS
# ============================================================

gt_pairs = []

for row in gt_sample.itertuples(index=False):

    if pd.isna(row.matched_entity_ids):
        continue

    matched_ids = str(row.matched_entity_ids).split(",")

    for matched_id in matched_ids:

        matched_id = matched_id.strip()

        if matched_id:
            gt_pairs.append({
                "source1_entity_id": row.source1_entity_id,
                "matched_entity_id": matched_id,
                "source": matched_id[:2]
            })

gt_pairs = pd.DataFrame(
    gt_pairs,
    columns=[
        "source1_entity_id",
        "matched_entity_id",
        "source"
    ]
)

print(f"Total true match pairs: {len(gt_pairs):,}")

print("\nTrue matches by source:")
print(gt_pairs["source"].value_counts())

display(gt_pairs.head(10))

# ============================================================
# STEP 11: CALCULATE CANDIDATE RECALL
# ============================================================

candidate_pairs = candidates.rename(
    columns={
        "candidate_entity_id": "matched_entity_id"
    }
)[
    [
        "source1_entity_id",
        "matched_entity_id"
    ]
].drop_duplicates()

# Match candidates against ground truth
recall_check = gt_pairs.merge(
    candidate_pairs,
    on=[
        "source1_entity_id",
        "matched_entity_id"
    ],
    how="left",
    indicator=True
)

recall_check["found"] = (
    recall_check["_merge"] == "both"
)

total_true = len(recall_check)
retrieved_true = recall_check["found"].sum()
missed_true = total_true - retrieved_true

overall_recall = (
    retrieved_true / total_true
    if total_true > 0
    else 0
)

print("=" * 60)
print("CANDIDATE RECALL")
print("=" * 60)

print(f"Total true match pairs : {total_true:,}")
print(f"Retrieved true matches : {retrieved_true:,}")
print(f"Missed true matches    : {missed_true:,}")
print(f"Candidate recall       : {overall_recall:.4%}")

# ============================================================
# STEP 12: SOURCE-SPECIFIC RECALL
# ============================================================

for source in ["S2", "S3"]:

    subset = recall_check[
        recall_check["source"] == source
    ]

    total = len(subset)
    found = subset["found"].sum()

    recall = (
        found / total
        if total > 0
        else 0
    )

    print(
        f"{source} candidate recall: {recall:.4%}"
    )
    print(
        f"{source} true pairs: {total:,}"
    )
    print(
        f"{source} retrieved: {found:,}"
    )
    print()

# ============================================================
# STEP 13: CANDIDATE COUNT DISTRIBUTION
# ============================================================

candidate_counts = (
    candidates
    .groupby(
        ["source1_entity_id", "candidate_source"]
    )
    .size()
    .unstack(fill_value=0)
)

if "S2" not in candidate_counts.columns:
    candidate_counts["S2"] = 0

if "S3" not in candidate_counts.columns:
    candidate_counts["S3"] = 0

candidate_counts["TOTAL"] = (
    candidate_counts["S2"] +
    candidate_counts["S3"]
)

print("Candidate statistics:")
print(candidate_counts["TOTAL"].describe())

print("\nCandidate count percentiles:")

display(
    candidate_counts["TOTAL"].quantile(
        [
            0.00,
            0.25,
            0.50,
            0.75,
            0.90,
            0.95,
            0.99,
            1.00
        ]
    )
)

# ============================================================
# STEP 14A: INSTALL FAISS
# ============================================================

!pip install -q faiss-cpu

# ============================================================
# STEP 14B: VERIFY FAISS
# ============================================================

import faiss

print("FAISS installed successfully!")
print("FAISS version:", faiss.__version__)

# ============================================================
# STEP 15: CHECK KERNEL STATE
# ============================================================

print("s2_index exists:", "s2_index" in globals())
print("s3_index exists:", "s3_index" in globals())
print("normalize_name exists:", "normalize_name" in globals())
print("s1_sample exists:", "s1_sample" in globals())

import faiss
print("FAISS version:", faiss.__version__)

# ============================================================
# STEP 16A: PREPARE UNIQUE NAMES FOR FUZZY RETRIEVAL
# ============================================================

import numpy as np
import pandas as pd
import time
import gc

print("Preparing unique normalized names...")

# Get unique keys from our existing exact indexes
s2_unique_names = list(s2_index.keys())
s3_unique_names = list(s3_index.keys())

# Each key is:
# (normalized_name, country)

s2_name_country = pd.DataFrame(
    s2_unique_names,
    columns=["name_norm", "country"]
)

s3_name_country = pd.DataFrame(
    s3_unique_names,
    columns=["name_norm", "country"]
)

print(f"S2 unique name+country keys: {len(s2_name_country):,}")
print(f"S3 unique name+country keys: {len(s3_name_country):,}")

display(s2_name_country.head())

# ============================================================
# STEP 17: BUILD COUNTRY-SPECIFIC TF-IDF INDEXES
# ============================================================

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors
import gc
import time

def build_country_tfidf_indexes(name_country_df):
    """
    Build sparse character TF-IDF + cosine nearest-neighbor
    indexes separately for each country.
    """

    indexes = {}

    countries = (
        name_country_df["country"]
        .dropna()
        .unique()
    )

    print(f"Countries found: {list(countries)}")

    for country in countries:

        print(f"\nBuilding index for: {country}")

        subset = name_country_df[
            name_country_df["country"] == country
        ].copy()

        subset = subset.reset_index(drop=True)

        print(
            f"Unique names: {len(subset):,}"
        )

        # Check if there are enough documents for TF-IDF Vectorizer (min_df is 2)
        if len(subset) < 2:
            print(f"Skipping TF-IDF index for {country} due to insufficient unique names ({len(subset):,})")
            continue # Skip to the next country

        vectorizer = TfidfVectorizer(
            analyzer="char",
            ngram_range=(2, 5),
            min_df=2,
            dtype=np.float32
        )

        start = time.time()

        matrix = vectorizer.fit_transform(
            subset["name_norm"]
        )

        print(
            f"TF-IDF shape: {matrix.shape}"
        )

        nn = NearestNeighbors(
            metric="cosine",
            algorithm="brute",
            n_jobs=-1
        )

        nn.fit(matrix)

        elapsed = time.time() - start

        indexes[country] = {
            "names": subset,
            "vectorizer": vectorizer,
            "matrix": matrix,
            "nn": nn
        }

        print(
            f"Finished {country} "
            f"in {elapsed / 60:.2f} minutes"
        )

        del subset
        gc.collect()

    return indexes

# ============================================================
# FIX: RECREATE SOURCE 2 NAME + COUNTRY TABLE
# ============================================================

print("Recreating s2_name_country from existing s2_index...")

s2_unique_names = list(s2_index.keys())

s2_name_country = pd.DataFrame(
    s2_unique_names,
    columns=["name_norm", "country"]
)

print(
    f"S2 unique name+country keys: "
    f"{len(s2_name_country):,}"
)

display(s2_name_country.head())

# ============================================================
# FIX: REBUILD SOURCE 3 EXACT INDEX
# ============================================================

print("Rebuilding Source 3 exact index...")

s3_index = build_name_country_index(
    DATA_DIR / "train_source3.tsv"
)

print("\nSource 3 exact index rebuilt!")

# ============================================================
# RECREATE SOURCE 3 NAME + COUNTRY TABLE
# ============================================================

s3_unique_names = list(s3_index.keys())

s3_name_country = pd.DataFrame(
    s3_unique_names,
    columns=["name_norm", "country"]
)

print(
    f"S3 unique name+country keys: "
    f"{len(s3_name_country):,}"
)

display(s3_name_country.head())

# ============================================================
# STEP 19: BUILD SOURCE 3 FUZZY INDEX
# ============================================================

print("Building Source 3 fuzzy indexes...")

s3_fuzzy_indexes = build_country_tfidf_indexes(
    s3_name_country
)

print("\nSource 3 fuzzy indexes ready!")

# ============================================================
# STEP 14A: CHECK SOURCE 2 STATE
# ============================================================

print("s2_index exists:", "s2_index" in globals())
print("s2_name_country exists:", "s2_name_country" in globals())

# ============================================================
# STEP 14B: RECREATE SOURCE 2 NAME + COUNTRY TABLE
# ============================================================

print("Recreating s2_name_country...")

s2_unique_names = list(s2_index.keys())

s2_name_country = pd.DataFrame(
    s2_unique_names,
    columns=["name_norm", "country"]
)

print(
    f"S2 unique name+country keys: "
    f"{len(s2_name_country):,}"
)

display(s2_name_country.head())

# ============================================================
# STEP 14C: RECREATE FUZZY INDEX FUNCTION
# ============================================================

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors
import time
import gc
import numpy as np
import pandas as pd


def build_country_tfidf_indexes(name_country_df):
    """
    Build sparse character TF-IDF + cosine nearest-neighbor
    indexes separately for each country.
    """

    indexes = {}

    countries = (
        name_country_df["country"]
        .dropna()
        .unique()
    )

    print(f"Countries found: {list(countries)}")

    for country in countries:

        print(f"\nBuilding index for: {country}")

        subset = name_country_df[
            name_country_df["country"] == country
        ].copy()

        subset = subset.reset_index(drop=True)

        print(
            f"Unique names: {len(subset):,}"
        )

        vectorizer = TfidfVectorizer(
            analyzer="char",
            ngram_range=(2, 5),
            min_df=2,
            dtype=np.float32
        )

        start = time.time()

        matrix = vectorizer.fit_transform(
            subset["name_norm"]
        )

        print(
            f"TF-IDF shape: {matrix.shape}"
        )

        nn = NearestNeighbors(
            metric="cosine",
            algorithm="brute",
            n_jobs=-1
        )

        nn.fit(matrix)

        elapsed = time.time() - start

        indexes[country] = {
            "names": subset,
            "vectorizer": vectorizer,
            "matrix": matrix,
            "nn": nn
        }

        print(
            f"Finished {country} "
            f"in {elapsed / 60:.2f} minutes"
        )

        del subset
        gc.collect()

    return indexes


print("build_country_tfidf_indexes() is ready!")

# ============================================================
# STEP 14D: CHECK SOURCE 2 DATA
# ============================================================

print("s2_index exists:", "s2_index" in globals())
print("s2_name_country exists:", "s2_name_country" in globals())
print("s3_fuzzy_indexes exists:", "s3_fuzzy_indexes" in globals())

if "s2_name_country" in globals():
    print(
        "S2 unique name+country keys:",
        len(s2_name_country)
    )

"""### Steps to Push your Colab Notebook to GitHub

1.  **Save your current Colab notebook**: Make sure your current notebook is saved (e.g., `File` -> `Save` or `File` -> `Save a copy in GitHub`). For the following steps, let's assume you save it to the `/content/` directory with the name `my_amazon_ml_challenge.ipynb`.

2.  **Set up a local Git repository**: We'll clone your target repository into a new directory and then copy your notebook into it.
"""

# Commented out IPython magic to ensure Python compatibility.
# IMPORTANT: Before running, ensure your notebook is saved (File -> Save)!

# 1. Change directory into the repository where the notebook resides
# %cd /content/Amazon--ML---challenge-/

# 2. Configure your Git user name and email (if you haven't already)
# Replace with your actual name and email
!git config user.email "your_email@example.com"
!git config user.name "Your Name"

# 3. Add the notebook file, commit, and push
# Replace <YOUR_PERSONAL_ACCESS_TOKEN> with your actual GitHub Personal Access Token
# If your default branch is 'master', change 'main' to 'master' in the push command
!git add "amazon-ml-challenge-dataset-training.ipynb" # Explicitly add the notebook file
!git commit -m "Update Colab notebook: amazon-ml-challenge-dataset-training.ipynb"
!git push "https://<YOUR_PERSONAL_ACCESS_TOKEN>@github.com/ShreeNithiB/Amazon--ML---challenge-.git" main

print("--------------------------------------------------------------------------------")
print("Please ensure you've saved your notebook (File -> Save) before running.")
print("Then, replace <YOUR_PERSONAL_ACCESS_TOKEN> with your actual GitHub Personal Access Token.")
print("Also, replace 'your_email@example.com' and 'Your Name' with your Git credentials.")
print("If your default branch is 'master', change 'main' to 'master' in the git push command.")
print("Re-run this cell after making these changes.")

"""### Important Notes:

*   **GitHub Credentials**: When you run `!git push`, you will likely be prompted to enter your GitHub username and Personal Access Token (PAT). GitHub no longer supports password authentication for Git operations. You'll need to generate a PAT from your GitHub settings if you don't have one.
*   **Notebook Filename**: Ensure you replace `my_amazon_ml_challenge.ipynb` with the exact name you saved your Colab notebook as.
*   **Branch Name**: The command `!git push origin main` assumes your repository's default branch is `main`. If it's `master` (or another name), adjust the command accordingly.
"""

!git push

!git status